#!/bin/sh
set -e

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  printf ".env already exists. Overwrite? [y/N] "
  read -r answer
  case "$answer" in
    [yY]) ;;
    *) echo "Aborted."; exit 0 ;;
  esac
fi

SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")

cat > "$ENV_FILE" <<EOF
# Generated by generate_env.sh — do not commit this file
SECRET_KEY=${SECRET_KEY}

# Number of gunicorn worker processes (default: 2)
# GUNICORN_WORKERS=2
EOF

echo ".env created with a secure SECRET_KEY."
